{% set version = "0.2.8.2" %}

package:
    name: dill
    version: {{ version }}

source:
    url: https://pypi.io/packages/source/d/dill/dill-{{ version }}.tar.gz
    sha256: 624dc244b94371bb2d6e7f40084228a2edfff02373fe20e018bef1ee92fdd5b3

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip
    run:
        - python
        - pyreadline  # [win]

test:
    imports:
        - dill

about:
    home: http://www.cacr.caltech.edu/~mmckerns
    license: BSD 3-Clause
    license_file: LICENSE
    summary: 'A utility for serialization of python objects.'

extra:
    recipe-maintainers:
        - ocefpaf
        - tupui
