{% set version = "0.2.6" %}

package:
    name: dill
    version: {{ version }}

source:
    fn: dill-{{ version }}.zip
    url: https://pypi.io/packages/source/d/dill/dill-{{ version }}.zip
    sha256: 6c1ccca68be483fa8c66e85a89ffc850206c26373aa77a97b83d8d0994e7f1fd

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pyreadline  # [win]

test:
    imports:
        - dill

about:
    home: http://www.cacr.caltech.edu/~mmckerns
    license: BSD 3-Clause
    license_file: LICENSE
    summary: 'A utility for serialization of python objects.'

extra:
    recipe-maintainers:
        - DanCodigaMWRA
        - ocefpaf
