travis:
  secure:
    BINSTAR_TOKEN: DitnZRnSiTgGpvfj2b9eMR7f+9d6VR5ZGiXCc6TuCBQFuucM4C9Y2j8sVwAqph4PFYnTvVRNHbzKrmYsPVMHTp51+KAjhjSfYOmsV0ygbpSXylz73ti/pfIqF75PAH5IiakZEnWEXWps4HdL+RfMwZ9auwWOIaXzPOqvis0u9POwYF2etVQmVSz97QPMHjrQTkshBW8VSwBHlzBw4btrOPmUlfgm3vnUCOVFZl8VPzX/mPIOpNEl2hTFKhwzrNn4P2W4sGtbET1xKo/8QpOqnCMRLKtn61NPNIEB0OV0vKLwfM+/0BBXqeVmn5XDqDIrxpJ0lQz6obEbRI/LtK4+1JnogQ/t8lby45NVnYB6Di5pySmyrm6LZB1vQa2Pw658+/T643mEXqnj0NeaA/+V5kKz8aKMaPuxGut6+N3quDQfmACiJXwHY+2RCo4KJNxC68DBxvRLGDIeNvws3C8hOJEjeji9a5v3W4lNk2IK2OvTphayK+I/CqKRem0kX6YvlwTH4MNMevyteaetL4vaNyCIuonjTk/CMyt1o1CDHRPvJh5kQdXA7CxWwtf2wm1i2YtcWuhBEFJ/2zFKa2wTtn4mc0U0rXzUgi9dKhfoIxp17olsibaTT2Uvro1XuiJ5juT5M6RyPV5e6ysO0Rd+XXwAvSxOXu26Do2e7eqRizg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
