travis:
  secure:
    BINSTAR_TOKEN: GoE44S78l/MY5M4aCvBscYLsJ/fZl3zqheDpWbbfW0DTsdYlCpi5rxtojkV5CMEa5mWw+/wM458inIC80FZngYHkOQQZGZzMdLvW8UjN0ovDcaQzuVirMzkGlFrC4R5NPvlyWPesjJxfoRztfma/R6LLM6JdUPzDy00ykpCDnWLJHZgaSQrpkj8f7W7vT7OvWdVQzpvLe49Z0YwousmDzKErNu5leTdJWXfnwJuPp1iB+w9EVC9i6HsV43j3+rUlblqSpea5rb0OpuDT68yXj8F0aKe76GW/PJQwgeK7ujKD8adCbzG1yB9nP7yuRKpy4kxJSOXiQazXGajR2goPNRAF38WftxxX6NPCWYrd3FiSSoQfGDmfh4yVO+bMv6yIFhaJxNiiPtNrk+RNLDvKauc88qfvaHvpUAvESYbGZGbGsgb1NfGnM3ZHdU0ocLxyyifUF25uFuYChR+PSyAN1PBpILxCzbqM2W++/BWiI2KQxNnVbNrtDYQCdl0/F4FFQQCLtI6Gfmanq2Kfu/l8kT3XtPxtaHmc7rkZosDjQyDVnwHddsw5W/vOhPm1C4B3E1nJD4Ujtr2F+avvPaYRoFLXlhmstyPqvH2MZA/InJLZ9uyLQnwgJUI84d95xWhxMo0Pfu/nTpxaKU/JLINm/c3uOrqPjILG0yO4R42j4wA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
